CREATE TABLE IF NOT EXISTS products (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 category TEXT NOT NULL DEFAULT 'ساعت مردانه',
 price TEXT NOT NULL DEFAULT '',
 badge TEXT NOT NULL DEFAULT '',
 description TEXT NOT NULL DEFAULT '',
 image_key TEXT NOT NULL DEFAULT '',
 available INTEGER NOT NULL DEFAULT 1,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_products_available ON products(available);
