const J=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store",...h}});
const body=async r=>{try{return await r.json()}catch{return{}}};
const hash=async p=>{const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode("avan:"+p));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")};
const token=()=>{const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,"0")).join("")};
const ck=(r,n)=>{const x=(r.headers.get("Cookie")||"").split(";").map(x=>x.trim()).find(x=>x.startsWith(n+"="));return x?decodeURIComponent(x.split("=")[1]):null};
async function me(r,e){const t=ck(r,"avan_session");if(!t)return null;return e.DB.prepare(`SELECT u.id,u.name,u.phone,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>datetime('now')`).bind(t).first()}
const setck=t=>`avan_session=${encodeURIComponent(t)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`;
const products=async(e,u)=>{let sql=`SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.active=1`,a=[];const q=u.searchParams.get("q"),b=u.searchParams.get("brand"),c=u.searchParams.get("category");if(q){sql+=` AND (p.name LIKE ? OR p.brand LIKE ? OR p.sku LIKE ?)`;a.push(`%${q}%`,`%${q}%`,`%${q}%`)}if(b){sql+=` AND p.brand=?`;a.push(b)}if(c){sql+=` AND c.slug=?`;a.push(c)}sql+=` ORDER BY p.featured DESC,p.id DESC LIMIT 100`;const {results=[]}=await e.DB.prepare(sql).bind(...a).all();return J(results.map(p=>({...p,gallery:JSON.parse(p.gallery||"[]")})))};
async function admin(req,e,u){
 const A=(m,p)=>req.method===m&&u.pathname===p;
 if(A("GET","/api/admin/dashboard")){const q=await Promise.all([e.DB.prepare("SELECT COUNT(*) n FROM products").first(),e.DB.prepare("SELECT COUNT(*) n FROM orders").first(),e.DB.prepare("SELECT COUNT(*) n FROM users WHERE role='customer'").first(),e.DB.prepare("SELECT COALESCE(SUM(total),0) n FROM orders WHERE payment_status='paid'").first()]);return J({products:q[0].n,orders:q[1].n,customers:q[2].n,revenue:q[3].n})}
 if(A("GET","/api/admin/products")){const {results=[]}=await e.DB.prepare("SELECT * FROM products ORDER BY id DESC").all();return J(results)}
 if(req.method==="POST"&&u.pathname==="/api/admin/products"){const b=await body(req);if(!b.name||!b.brand)return J({error:"نام و برند الزامی است"},400);const slug=(b.slug||`${b.brand}-${b.name}-${Date.now()}`).replace(/[^a-zA-Z0-9\u0600-\u06ff]+/g,"-");await e.DB.prepare(`INSERT INTO products(category_id,brand,name,slug,description,price,compare_price,stock,sku,image,gallery,featured,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(b.categoryId||null,b.brand,b.name,slug,b.description||"",+b.price||0,b.comparePrice||null,+b.stock||0,b.sku||"",b.image||"",JSON.stringify(b.gallery||[]),b.featured?1:0,b.active===0?0:1).run();return J({ok:true})}
 if(req.method==="PATCH"&&u.pathname.startsWith("/api/admin/products/")){const id=u.pathname.split("/").pop(),b=await body(req),map={categoryId:"category_id",brand:"brand",name:"name",description:"description",price:"price",comparePrice:"compare_price",stock:"stock",sku:"sku",image:"image",featured:"featured",active:"active"};const f=[],a=[];for(const [k,col] of Object.entries(map))if(b[k]!==undefined){f.push(`${col}=?`);a.push(["featured","active"].includes(k)?(b[k]?1:0):b[k])}if(b.gallery!==undefined){f.push("gallery=?");a.push(JSON.stringify(b.gallery))}if(!f.length)return J({error:"تغییری ارسال نشده"},400);f.push("updated_at=CURRENT_TIMESTAMP");a.push(id);await e.DB.prepare(`UPDATE products SET ${f.join(",")} WHERE id=?`).bind(...a).run();return J({ok:true})}
 if(req.method==="DELETE"&&u.pathname.startsWith("/api/admin/products/")){await e.DB.prepare("DELETE FROM products WHERE id=?").bind(u.pathname.split("/").pop()).run();return J({ok:true})}
 if(A("GET","/api/admin/orders")){const {results=[]}=await e.DB.prepare("SELECT * FROM orders ORDER BY id DESC LIMIT 300").all();return J(results)}
 if(req.method==="PATCH"&&u.pathname.startsWith("/api/admin/orders/")){const id=u.pathname.split("/").pop(),b=await body(req),f=[],a=[];for(const k of ["status","payment_status","tracking_code"])if(b[k]!==undefined){f.push(`${k}=?`);a.push(b[k])}if(!f.length)return J({error:"تغییری ارسال نشده"},400);a.push(id);await e.DB.prepare(`UPDATE orders SET ${f.join(",")},updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(...a).run();return J({ok:true})}
 if(A("GET","/api/admin/customers")){const {results=[]}=await e.DB.prepare("SELECT id,name,phone,email,created_at FROM users WHERE role='customer' ORDER BY id DESC").all();return J(results)}
 if(A("GET","/api/admin/categories")){const {results=[]}=await e.DB.prepare("SELECT * FROM categories ORDER BY sort_order,id").all();return J(results)}
 if(req.method==="POST"&&u.pathname==="/api/admin/categories"){const b=await body(req);await e.DB.prepare("INSERT INTO categories(name,slug,image,sort_order) VALUES(?,?,?,?)").bind(b.name,b.slug,b.image||"",+b.sortOrder||0).run();return J({ok:true})}
 if(A("GET","/api/admin/coupons")){const {results=[]}=await e.DB.prepare("SELECT * FROM coupons ORDER BY id DESC").all();return J(results)}
 if(req.method==="POST"&&u.pathname==="/api/admin/coupons"){const b=await body(req);await e.DB.prepare("INSERT INTO coupons(code,type,value,min_order,max_uses,expires_at) VALUES(?,?,?,?,?,?)").bind(String(b.code).toUpperCase(),b.type||"percent",+b.value||0,+b.minOrder||0,b.maxUses||null,b.expiresAt||null).run();return J({ok:true})}
 return J({error:"Admin API not found"},404)
}
export default {async fetch(req,e){
 const u=new URL(req.url);
 try{
  if(u.pathname.startsWith("/api/")){
   if(u.pathname==="/api/auth/register"&&req.method==="POST"){const b=await body(req);if(!b.name||!b.phone||!b.password||b.password.length<6)return J({error:"اطلاعات ثبت‌نام ناقص است"},400);if(await e.DB.prepare("SELECT id FROM users WHERE phone=?").bind(b.phone).first())return J({error:"این شماره قبلاً ثبت شده"},409);const r=await e.DB.prepare("INSERT INTO users(name,phone,email,password_hash) VALUES(?,?,?,?)").bind(b.name,b.phone,b.email||"",await hash(b.password)).run();const t=token();await e.DB.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,datetime('now','+7 days'))").bind(t,r.meta.last_row_id).run();return J({ok:true,user:{id:r.meta.last_row_id,name:b.name,phone:b.phone,role:"customer"}},200,{"set-cookie":setck(t)})}
   if(u.pathname==="/api/auth/login"&&req.method==="POST"){const b=await body(req),x=await e.DB.prepare("SELECT id,name,phone,email,role FROM users WHERE phone=? AND password_hash=?").bind(b.phone,await hash(b.password||"")).first();if(!x)return J({error:"شماره یا رمز اشتباه است"},401);const t=token();await e.DB.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,datetime('now','+7 days'))").bind(t,x.id).run();return J({ok:true,user:x},200,{"set-cookie":setck(t)})}
   if(u.pathname==="/api/auth/logout"){const t=ck(req,"avan_session");if(t)await e.DB.prepare("DELETE FROM sessions WHERE id=?").bind(t).run();return J({ok:true},200,{"set-cookie":"avan_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0"})}
   if(u.pathname==="/api/auth/me")return J({user:await me(req,e)});
   if(u.pathname==="/api/products")return products(e,u);
   if(u.pathname==="/api/categories"){const {results=[]}=await e.DB.prepare("SELECT * FROM categories WHERE active=1 ORDER BY sort_order,id").all();return J(results)}
   const user=await me(req,e);
   if(u.pathname==="/api/cart"){if(!user)return J({error:"ورود لازم است"},401);if(req.method==="GET"){const c=await e.DB.prepare("SELECT items FROM carts WHERE user_id=?").bind(user.id).first();return J({items:c?JSON.parse(c.items):[]})}const b=await body(req);await e.DB.prepare("INSERT INTO carts(user_id,items) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET items=excluded.items,updated_at=CURRENT_TIMESTAMP").bind(user.id,JSON.stringify(b.items||[])).run();return J({ok:true})}
   if(u.pathname==="/api/orders"&&req.method==="GET"){if(!user)return J({error:"ورود لازم است"},401);const {results=[]}=await e.DB.prepare("SELECT * FROM orders WHERE user_id=? ORDER BY id DESC").bind(user.id).all();return J(results)}
   if(u.pathname==="/api/orders"&&req.method==="POST"){if(!user)return J({error:"ورود لازم است"},401);const b=await body(req);if(!b.items?.length)return J({error:"سبد خرید خالی است"},400);let total=0,verified=[];for(const x of b.items){const p=await e.DB.prepare("SELECT id,name,brand,price,stock,image FROM products WHERE id=? AND active=1").bind(x.productId).first();const qty=Math.max(1,Math.min(99,+x.qty||1));if(!p||p.stock<qty)return J({error:"محصول یا موجودی کافی نیست"},400);total+=p.price*qty;verified.push({...p,qty})}const num="AVN-"+Date.now().toString(36).toUpperCase();const r=await e.DB.prepare("INSERT INTO orders(user_id,order_number,total,receiver,phone,province,city,address,postal_code,note) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(user.id,num,total,b.receiver,b.phone,b.province,b.city,b.address,b.postalCode||"",b.note||"").run();for(const p of verified){await e.DB.prepare("INSERT INTO order_items(order_id,product_id,product_name,brand,price,qty,image) VALUES(?,?,?,?,?,?,?)").bind(r.meta.last_row_id,p.id,p.name,p.brand,p.price,p.qty,p.image).run();await e.DB.prepare("UPDATE products SET stock=stock-? WHERE id=?").bind(p.qty,p.id).run()}await e.DB.prepare("INSERT INTO carts(user_id,items) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET items='[]'").bind(user.id,"[]").run();return J({ok:true,orderNumber:num,total})}
   if(u.pathname==="/api/profile"&&req.method==="GET"){if(!user)return J({error:"ورود لازم است"},401);return J({user})}
   if(u.pathname==="/api/profile"&&req.method==="PATCH"){if(!user)return J({error:"ورود لازم است"},401);const b=await body(req);await e.DB.prepare("UPDATE users SET name=?,email=? WHERE id=?").bind(b.name||user.name,b.email||"",user.id).run();return J({ok:true})}
   if(u.pathname==="/api/addresses"&&req.method==="GET"){if(!user)return J({error:"ورود لازم است"},401);const {results=[]}=await e.DB.prepare("SELECT * FROM addresses WHERE user_id=? ORDER BY id DESC").bind(user.id).all();return J(results)}
   if(u.pathname==="/api/addresses"&&req.method==="POST"){if(!user)return J({error:"ورود لازم است"},401);const b=await body(req);if(!b.receiver||!b.phone||!b.province||!b.city||!b.address)return J({error:"اطلاعات آدرس ناقص است"},400);await e.DB.prepare("INSERT INTO addresses(user_id,title,receiver,phone,province,city,address,postal_code) VALUES(?,?,?,?,?,?,?,?)").bind(user.id,b.title||"آدرس",b.receiver,b.phone,b.province,b.city,b.address,b.postalCode||"").run();return J({ok:true})}
   if(u.pathname.startsWith("/api/addresses/")&&req.method==="DELETE"){if(!user)return J({error:"ورود لازم است"},401);await e.DB.prepare("DELETE FROM addresses WHERE id=? AND user_id=?").bind(u.pathname.split("/").pop(),user.id).run();return J({ok:true})}
   if(u.pathname.startsWith("/api/orders/")&&req.method==="GET"){if(!user)return J({error:"ورود لازم است"},401);const id=u.pathname.split("/").pop();const o=await e.DB.prepare("SELECT * FROM orders WHERE id=? AND user_id=?").bind(id,user.id).first();if(!o)return J({error:"سفارش پیدا نشد"},404);const {results=[]}=await e.DB.prepare("SELECT * FROM order_items WHERE order_id=?").bind(id).all();return J({...o,items:results})}
   if(u.pathname.startsWith("/api/products/")&&req.method==="GET"){const id=u.pathname.split("/").pop();const p=await e.DB.prepare("SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.id=? AND p.active=1").bind(id).first();if(!p)return J({error:"محصول پیدا نشد"},404);return J({...p,gallery:JSON.parse(p.gallery||"[]")})}
   if(u.pathname.startsWith("/api/admin/")){if(!user||user.role!=="admin")return J({error:"دسترسی مدیر لازم است"},403);return admin(req,e,u,user)}
   return J({error:"API not found"},404)
  }
  return e.ASSETS.fetch(req)
 }catch(err){console.error(err);return J({error:"خطای سرور",detail:err.message},500)}
}}